/**
 * Cookie Extraction & Netscape Format Exporter for YoutubeDL-GUI
 */

const crossBrowserCookieApi = typeof browser !== 'undefined' ? browser : chrome;

async function getNetscapeCookiesForUrl(url) {
  if (!url || !crossBrowserCookieApi.cookies) return '';

  try {
    const urlObj = new URL(url);
    const domain = urlObj.hostname;

    const domainsToQuery = new Set();
    domainsToQuery.add(domain);
    domainsToQuery.add('.' + domain);

    const parts = domain.split('.');
    if (parts.length >= 2) {
      const rootDomain = parts.slice(-2).join('.');
      domainsToQuery.add(rootDomain);
      domainsToQuery.add('.' + rootDomain);
    }

    if (domain.includes('youtube.com') || domain.includes('youtu.be')) {
      domainsToQuery.add('.google.com');
      domainsToQuery.add('google.com');
      domainsToQuery.add('.youtube.com');
      domainsToQuery.add('youtube.com');
      domainsToQuery.add('.accounts.google.com');
    }

    const cookiesMap = new Map();

    // 1. Query by domain
    for (const d of domainsToQuery) {
      try {
        const cookies = await crossBrowserCookieApi.cookies.getAll({ domain: d });
        for (const c of cookies) {
          if (c && c.name) {
            const key = `${c.domain}|${c.path}|${c.name}`;
            cookiesMap.set(key, c);
          }
        }
      } catch { }
    }

    // 2. Query by full URL
    try {
      const urlCookies = await crossBrowserCookieApi.cookies.getAll({ url: url });
      for (const c of urlCookies) {
        if (c && c.name) {
          const key = `${c.domain}|${c.path}|${c.name}`;
          cookiesMap.set(key, c);
        }
      }
    } catch { }

    if (cookiesMap.size === 0) return '';

    // Standard Netscape HTTP Cookie File header expected by Python's http.cookiejar / yt-dlp
    let netscape = '# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by YoutubeDL-GUI Extension\n\n';
    
    for (const cookie of cookiesMap.values()) {
      if (!cookie.name) continue;

      let cDomain = cookie.domain || domain;
      const includeSubdomains = cDomain.startsWith('.') ? 'TRUE' : 'FALSE';
      const path = cookie.path || '/';
      const secure = cookie.secure ? 'TRUE' : 'FALSE';
      const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
      const name = String(cookie.name).replace(/[\r\n\t]+/g, '');
      const value = String(cookie.value || '').replace(/[\r\n]+/g, '');

      netscape += `${cDomain}\t${includeSubdomains}\t${path}\t${secure}\t${expiration}\t${name}\t${value}\n`;
    }

    return netscape;
  } catch (err) {
    console.warn('Erro ao extrair cookies para o domínio:', err);
    return '';
  }
}
